### ISSUE TITLE
Error in match(x, table, nomatch = 0L) :    'match' requires vector arguments

### ISSUE THREAD

**Issue by ghost** [irilenia/baerhunter#2]
Hi,

I have installed baerhunter package, as-well as necessary prerequisites from Bioconductor.

When I try to to run feature_file_editor() function I get the following output:

[1] "Extracted plus strand data from BAM files"
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments

I have tried this with the test setup that you proposed (data from Zonodo), as-well as with my own data.

This is the code I use to execute the function (own data):

feature_file_editor(bam_directory="sorted_bam/",  
                    original_annotation_file="168_GFF.gff",
                    annot_file_dir = "annotation_data/",
                    output_file="test_output.gff3", 
                    original_sRNA_annotation="ncRNA", 
                    low_coverage_cutoff=5, 
                    min_sRNA_length=40, 
                    high_coverage_cutoff=10, 
                    min_UTR_length=50, 
                    paired_end_data=FALSE, 
                    strandedness="stranded")

- all folders referred to are in my current working directory
- the sorted_bam directory contains only 1 x 3,000kb sorted .bam file 
- gff annotation is in GFF3 format

Would you happen to have any idea as to what is going wrong?

**Comment by ghost** [comment]
Here are the files I used:

[168_GFF.zip](https://github.com/irilenia/baerhunter/files/5388271/168_GFF.zip)

[subsample.sorted.zip](https://github.com/irilenia/baerhunter/files/5388273/subsample.sorted.zip)

**Comment by ghost** [comment]
Right I think I found a workaround.

I think there is an issue with my environment, as feature_file_editor works when I redefine the problematic functions (sRNA_calc & UTR_calc) and then I redefine feature_file_editor using the redefined functions.

For some reason when I call sRNA_calc/UTR_calc without redefinition, the error is thrown.

**Comment by irilenia** [comment]
Hi, I'm really sorry I didn't see this any earlier. It seems that you found a fix which is great as I wouldn't be able to say what was causing the problem! We will probably be doing some updating to baerhunter soon so might need to have a closer look at this issue. In the meantime, I'll close the issue, if you are happy with your solution.
Once again, sorry for the rather late reply.

**Comment by ghost** [comment]
No worries. I am happy for you to close the issue.
