### ISSUE TITLE
problem of function "feature_file_editor" 

### ISSUE THREAD

**Issue by wanjinhu** [irilenia/baerhunter#4]
hello there:
**when i run function "feature_file_editor" using the example data, there are some erro information like:**
```
[1] "Extracted plus strand data from BAM files"
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
```
**the code what i run is:**
```
feature_file_editor(bam_directory="output/simulations/paired_realistic_selected_sRNA_UTR/fc.20",  
                    original_annotation_file="Mycobacterium_tuberculosis_h37rv.ASM19595v2.40.chromosome.Chromosome.gff3",
                    annot_file_dir = "./data/",
                    output_file="output/simulations/paired_realistic_selected_sRNA_UTR/fc.20/mtb_5_10.gff3", "ncRNA", 
                    low_coverage_cutoff=5, 
                    high_coverage_cutoff=10, 
                    min_sRNA_length=40, 
                    min_UTR_length=50, 
                    paired_end_data=TRUE, 
                    strandedness="stranded")
```
the necessary files i already prepared, and i checked the source code of the function "feature_file_editor", maybe the function "major_features", "sRNA_calc" , "UTR_calc" or "strand_feature_editor" went wrong? i have no ideal what happened here. maybe someone can solve my problem?

the part of the function "feature_file_editor" like:
```
{
    plus_strand_peaks <- peak_union_calc(bam_location = bam_directory, 
        "+", low_coverage_cutoff, high_coverage_cutoff, min_sRNA_length, 
        paired_end_data, strandedness)
    print("Extracted plus strand data from BAM files")
    maj_plus_features <- major_features(original_annotation_file, 
        annot_file_directory = annot_file_dir, "+", original_sRNA_annotation)
    plus_sRNA <- sRNA_calc(maj_plus_features, "+", plus_strand_peaks)
    plus_UTR <- UTR_calc(maj_plus_features, "+", plus_strand_peaks, 
        min_sRNA_length)
    plus_annot_dataframe <- strand_feature_editor("+", plus_sRNA, 
        plus_UTR, maj_plus_features)
    print("Built plus strand annotation dataframe")
```
thanks a lot

**Comment by mirpedrol** [comment]
I'm having the same error. Were you able to solve the problem?
I would appreciate any help.

**Comment by Artgrigorov** [comment]
Same problem here

**Comment by Artgrigorov** [comment]
Yes, redefining functions helped, as was described in previous issue

**Comment by irilenia** [comment]
I am really sorry to get back to you on this so late. 
This is indeed the same issue that was raised in 2021 (issue now closed). The base match() function that is required by %in% is masked by IRanges' own match definition. At the moment, we resolve this by redefining the function (for example, you can source the R script containing the definition of feature_file_editor()) before running baerhunter but this does not seem like a great solution. However, it does allow you to run baerhunter. You simply cannot do it straight from github with devtools.

**Comment by irilenia** [comment]
We believe the problem with the match() function is now resolved by @jenjane118 's fixes. Branch merged on the 22nd of May 2022.
I will now close this issue. Thank you for your patience and input.
